import { ServiceConfig } from '@shared/schema';

export interface ConfigPreset {
  id: string;
  name: string;
  description: string;
  config: ServiceConfig;
}

export const configPresets: ConfigPreset[] = [
  {
    id: 'development',
    name: 'Development',
    description: 'All services with lower resources, ideal for local testing',
    config: {
      enableHealthChecks: true,
      restartPolicy: 'unless-stopped',
      networkName: 'librechat',
      searxng: {
        enabled: true,
        port: 8080,
        memoryLimit: '512MB',
        version: 'latest',
        apiKey: 'searxng-default-key-12345',
        customVolumes: '',
        customSettings: '',
      },
      jinaReader: {
        enabled: true,
        port: 3000,
        memoryLimit: '512MB',
        version: 'latest',
        timeout: 30,
        maxPages: 5,
        apiKey: 'jina-default-key-67890',
        customVolumes: '',
      },
      bgeReranker: {
        enabled: true,
        port: 8787,
        memoryLimit: '2GB',
        version: 'latest',
        modelType: 'BAAI/bge-reranker-base',
        maxBatchSize: 16,
        apiKey: 'reranker-default-key-abcde',
        customVolumes: '',
      },
    },
  },
  {
    id: 'production',
    name: 'Production',
    description: 'All services with higher resources, optimized for production workloads',
    config: {
      enableHealthChecks: true,
      restartPolicy: 'unless-stopped',
      networkName: 'librechat',
      searxng: {
        enabled: true,
        port: 8080,
        memoryLimit: '2GB',
        version: 'latest',
        apiKey: 'searxng-default-key-12345',
        customVolumes: '',
        customSettings: '',
      },
      jinaReader: {
        enabled: true,
        port: 3000,
        memoryLimit: '2GB',
        version: 'latest',
        timeout: 60,
        maxPages: 20,
        apiKey: 'jina-default-key-67890',
        customVolumes: '',
      },
      bgeReranker: {
        enabled: true,
        port: 8787,
        memoryLimit: '8GB',
        version: 'latest',
        modelType: 'BAAI/bge-reranker-v2-m3',
        maxBatchSize: 64,
        apiKey: 'reranker-default-key-abcde',
        customVolumes: '',
      },
    },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Only essential services with minimal resources',
    config: {
      enableHealthChecks: false,
      restartPolicy: 'unless-stopped',
      networkName: 'librechat',
      searxng: {
        enabled: true,
        port: 8080,
        memoryLimit: '512MB',
        version: 'latest',
        apiKey: 'searxng-default-key-12345',
        customVolumes: '',
        customSettings: '',
      },
      jinaReader: {
        enabled: true,
        port: 3000,
        memoryLimit: '512MB',
        version: 'latest',
        timeout: 30,
        maxPages: 5,
        apiKey: 'jina-default-key-67890',
        customVolumes: '',
      },
      bgeReranker: {
        enabled: false,
        port: 8787,
        memoryLimit: '2GB',
        version: 'latest',
        modelType: 'BAAI/bge-reranker-base',
        maxBatchSize: 16,
        apiKey: 'reranker-default-key-abcde',
        customVolumes: '',
      },
    },
  },
  {
    id: 'custom',
    name: 'Custom',
    description: 'Configure services manually',
    config: {
      enableHealthChecks: true,
      restartPolicy: 'unless-stopped',
      networkName: 'librechat',
      searxng: {
        enabled: true,
        port: 8080,
        memoryLimit: '1GB',
        version: 'latest',
        apiKey: 'searxng-default-key-12345',
        customVolumes: '',
        customSettings: '',
      },
      jinaReader: {
        enabled: true,
        port: 3000,
        memoryLimit: '1GB',
        version: 'latest',
        timeout: 30,
        maxPages: 10,
        apiKey: 'jina-default-key-67890',
        customVolumes: '',
      },
      bgeReranker: {
        enabled: true,
        port: 8787,
        memoryLimit: '4GB',
        version: 'latest',
        modelType: 'BAAI/bge-reranker-v2-m3',
        maxBatchSize: 32,
        apiKey: 'reranker-default-key-abcde',
        customVolumes: '',
      },
    },
  },
];
